name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: deploy in server
      uses: appleboy/ssh-action@master
      env: 
        BRANCH: ${{ steps.extract_branch.outputs.branch }}
        REPO: ${{ github.repository }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        envs: BRANCH,REPO
        script: |
          cd /home/ec2-user/star_kill/services/planesticud
          git clone https://github.com/$REPO
          cd /home/ec2-user/star_kill/services/$REPO
          git checkout $BRANCH
          git pull origin $BRANCH
          docker-compose build
          docker-compose up -d